name: e2e
on:
  push:
  workflow_dispatch:
jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt || true
          python -m pip install pytest pytest-playwright pytest-html playwright
          python -m playwright install --with-deps chromium
          mkdir -p artifacts
      - name: Run tests
        env:
          BASE_URL: https://www.saucedemo.com
        run: |
          python -m pytest -q --html=artifacts/report.html --self-contained-html
      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: qa-report
          path: artifacts/report.html
      - name: Upload Playwright traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            playwright-report/**
            test-results/**
          if-no-files-found: ignore
