name: ui-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        browser: [chromium, firefox, webkit]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install ${{ matrix.browser }}

      - name: Run Playwright tests
        run: |
          mkdir -p artifacts
          pytest -q --html=artifacts/report-${{ matrix.os }}-${{ matrix.browser }}.html --self-contained-html --maxfail=1 --disable-warnings

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ matrix.os }}-${{ matrix.browser }}
          path: artifacts/report-${{ matrix.os }}-${{ matrix.browser }}.html

      - name: Upload Playwright Traces (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: trace-${{ matrix.os }}-${{ matrix.browser }}
          path: test-results/
