name: ui-tests
on:
  push:
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      BASE_URL: https://www.saucedemo.com
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt || true
          python -m pip install pytest pytest-html pytest-playwright playwright
      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium
      - name: Run tests and generate HTML
        run: |
          mkdir -p artifacts
          set +e
          pytest -q --html=artifacts/report.html --self-contained-html
          echo "PYTEST_EXIT=$?" >> $GITHUB_ENV
          set -e
      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: artifacts/report.html
          if-no-files-found: warn
      - name: Fail job if tests failed
        if: ${{ env.PYTEST_EXIT != '0' }}
        run: exit 1
